# Generated by Django 5.2.8 on 2025-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
