# Generated by Django 5.2.8 on 2025-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_contacts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
