# Generated by Django 5.2.8 on 2025-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_contacts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
