# Generated by Django 5.2.8 on 2025-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_contacts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
