# Generated by Django 5.2.8 on 2025-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_contacts_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
